JandiGoorm/jandi_band_backend

src/main/java/com/jandi/band_backend/club/controller/ClubController.java
src/main/java/com/jandi/band_backend/club/dto/ClubRespDTO.java
src/main/java/com/jandi/band_backend/club/dto/ClubSimpleRespDTO.java
src/main/java/com/jandi/band_backend/club/dto/ClubUpdateReqDTO.java
src/main/java/com/jandi/band_backend/club/service/ClubService.java
src/main/java/com/jandi/band_backend/global/util/TimeUtil.java
src/main/java/com/jandi/band_backend/univ/dto/UniversityRespDTO.java

예시:
1) src/main/java/com/jandi/band_backend/club/dto/ClubRespDTO.java
```java
package com.jandi.band_backend.club.dto;
import com.jandi.band_backend.club.entity.Club;
import com.jandi.band_backend.club.entity.ClubPhoto;
import com.jandi.band_backend.global.util.TimeUtil;
import com.jandi.band_backend.univ.dto.UniversityRespDTO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import java.time.ZonedDateTime;
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClubRespDTO {
private Integer id;
private String name;
private UniversityRespDTO university;
private Boolean isUnionClub;
private String chatroomUrl;
private String description;
private String instagramId;
private String photoUrl;
private Integer …
```

TimeUtil 추가 및 DTO 관련

---

src/main/java/com/jandi/band_backend/config/S3Config.java
src/main/java/com/jandi/band_backend/global/exception/ResourceNotFoundException.java
src/main/java/com/jandi/band_backend/health/HealthCheckController.java
src/main/java/com/jandi/band_backend/image/ImageController.java
src/main/java/com/jandi/band_backend/image/S3Service.java
src/main/java/com/jandi/band_backend/promo/controller/PromoController.java
src/main/java/com/jandi/band_backend/promo/dto/PromoImageRequest.java
src/main/java/com/jandi/band_backend/promo/dto/PromoRequest.java
src/main/java/com/jandi/band_backend/promo/dto/PromoResponse.java
src/main/java/com/jandi/band_backend/promo/repository/PromoRepository.java
src/main/java/com/jandi/band_backend/promo/service/PromoService.java
src/main/resources/application.properties.example

- Closes #이슈번호
- 아직 작업 중. API 명세서 작성 안 함.

Feat: 공연 홍보 CRUD 기능

---

src/main/java/com/jandi/band_backend/club/service/ClubService.java

FIX: 동아리 생성/수정에서 대표 사진 처리 로직 정리

---

src/main/java/com/jandi/band_backend/club/entity/Club.java
src/main/java/com/jandi/band_backend/club/entity/ClubMember.java
src/main/java/com/jandi/band_backend/manage/entity/ReportReason.java
src/main/java/com/jandi/band_backend/poll/entity/Poll.java
src/main/java/com/jandi/band_backend/poll/entity/Vote.java
src/main/java/com/jandi/band_backend/poll/repository/PollRepository.java
src/main/java/com/jandi/band_backend/promo/entity/PromoCommentLike.java
src/main/java/com/jandi/band_backend/promo/entity/PromoCommentReport.java
src/main/java/com/jandi/band_backend/promo/entity/PromoLike.java
src/main/java/com/jandi/band_backend/promo/entity/PromoReport.java
src/main/java/com/jandi/band_backend/team/entity/TeamEvent.java
src/main/java/com/jandi/band_backend/user/entity/Users.java

- 커밋, 변경 내역 참조
- Instant -> LocalDateTime 작업 중 변형된 코드 되돌림
- @Column(name = "created_at", nullable = false, updatable = false) 복원
- @Column(name = "updated_at", nullable = false) 복원 등
- PollRepository에서 Instant -> LocalDateTime 적용 (누락된 것으로 추정)

FIX: Instant -> LocalDateTime 작업 보완

---

docs/team-practice.md
src/main/java/com/jandi/band_backend/team/controller/PracticeScheduleController.java
src/main/java/com/jandi/band_backend/team/dto/PracticeScheduleRequest.java
src/main/java/com/jandi/band_backend/team/dto/PracticeScheduleResponse.java
src/main/java/com/jandi/band_backend/team/dto/TeamEventParticipantResponse.java
src/main/java/com/jandi/band_backend/team/repository/TeamEventRepository.java
src/main/java/com/jandi/band_backend/team/repository/TeamRepository.java
src/main/java/com/jandi/band_backend/team/service/PracticeScheduleService.java

feat: 곡 팀 연습 일정 CRUD

---

docs/my-page.md
docs/team-practice.md
src/main/java/com/jandi/band_backend/club/repository/ClubMemberRepository.java
src/main/java/com/jandi/band_backend/team/controller/PracticeScheduleController.java
src/main/java/com/jandi/band_backend/team/dto/PracticeScheduleRequest.java
src/main/java/com/jandi/band_backend/team/dto/PracticeScheduleResponse.java
src/main/java/com/jandi/band_backend/team/dto/TeamEventParticipantResponse.java
src/main/java/com/jandi/band_backend/team/repository/TeamEventRepository.java
src/main/java/com/jandi/band_backend/team/repository/TeamMemberRepository.java
src/main/java/com/jandi/band_backend/team/repository/TeamRepository.java
src/main/java/com/jandi/band_backend/team/service/PracticeScheduleService.java
src/main/java/com/jandi/band_backend/user/controller/MyPageController.java
src/main/java/com/jandi/band_backend/user/dto/MyClubResponse.java
src/main/java/com/jandi/band_backend/user/dto/MyTeamResponse.java
src/main/java/com/jandi/band_backend/user/service/MyPageService.java

feat: 내가 참여한 팀, 동아리 목록 조회 API

---

docs/club-teams.md
src/main/java/com/jandi/band_backend/team/controller/ClubTeamController.java
src/main/java/com/jandi/band_backend/team/dto/ClubTeamResponse.java
src/main/java/com/jandi/band_backend/team/repository/TeamEventRepository.java
src/main/java/com/jandi/band_backend/team/repository/TeamRepository.java
src/main/java/com/jandi/band_backend/team/service/ClubTeamService.java

feat: 동아리 곡 팀 목록 조회 API

---

src/main/java/com/jandi/band_backend/auth/controller/AuthController.java
src/main/java/com/jandi/band_backend/club/controller/ClubController.java
src/main/java/com/jandi/band_backend/global/CommonResponse.java
src/main/java/com/jandi/band_backend/global/GlobalExceptionHandler.java
src/main/java/com/jandi/band_backend/poll/controller/PollController.java
src/main/java/com/jandi/band_backend/promo/controller/PromoController.java
src/main/java/com/jandi/band_backend/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/jandi/band_backend/team/controller/PracticeScheduleController.java
src/main/java/com/jandi/band_backend/team/controller/TeamController.java
src/main/java/com/jandi/band_backend/univ/controller/RegionController.java
src/main/java/com/jandi/band_backend/univ/controller/UniversityController.java
src/main/java/com/jandi/band_backend/user/controller/MyPageController.java
src/main/java/com/jandi/band_backend/user/controller/UserController.java
src/main/java/com/jandi/band_backend/user/controller/UserTimetableController.java

- ApiResponse를 CommonResponse로 응답 형식 변경
- 위와 같음
- 스웨거의 @ApiResponse 어노테이션과 우리가 쓰던 공통 응답 객체 ApiResponse가 import에서 겹칠 수 있어 변경함

refactor: ApiResponse를 CommonResponse로 응답 형식 변경

---

src/main/java/com/jandi/band_backend/poll/dto/PollSongRespDTO.java
src/main/java/com/jandi/band_backend/poll/service/PollService.java

- PollSongRespDTO에 제안자 프사 추가
- 위와 같음
- 프론트엔드 요청
- suggester id와 name은 entity와 service에서 실질적으로 null이 될 수 없음을 확인하고 null check 제거

feat: PollSongRespDTO에 제안자 프사 추가

---

src/main/java/com/jandi/band_backend/club/controller/ClubEventController.java

feat:스웨거 관련 코드 추가
- Closes #이슈번호
- 스웨거 관련 코드를 추가

feat:스웨거 관련 코드 추가

---

src/main/java/com/jandi/band_backend/promo/repository/PromoPhotoRepository.java
src/main/java/com/jandi/band_backend/promo/service/PromoService.java

fix: 공연 홍보 이미지 기능 수정

---

src/main/java/com/jandi/band_backend/club/controller/ClubController.java
src/main/java/com/jandi/band_backend/club/service/ClubEventService.java
src/main/java/com/jandi/band_backend/global/util/PermissionValidationUtil.java
src/main/java/com/jandi/band_backend/global/util/UserValidationUtil.java
src/main/java/com/jandi/band_backend/poll/controller/PollController.java
src/main/java/com/jandi/band_backend/promo/service/PromoCommentService.java
src/main/java/com/jandi/band_backend/promo/service/PromoService.java
src/main/java/com/jandi/band_backend/team/controller/PracticeScheduleController.java
src/main/java/com/jandi/band_backend/team/controller/TeamController.java
src/main/java/com/jandi/band_backend/team/service/PracticeScheduleService.java
src/main/java/com/jandi/band_backend/team/service/TeamTimetableService.java
src/main/java/com/jandi/band_backend/user/service/UserService.java
src/main/java/com/jandi/band_backend/user/service/UserTimetableService.java

- 로그인을 제외한 로직에서 kakao_oauth_id 대신 user_id를 사용하도록
- ADMIN은 모든 수정/삭제 권한을 가지도록
- Page 객체를 JSON 직렬화할때 발생하는 문제를 해결하기 위해 PageImpl을 직접 변환하지 않고 구조화된 PageRespDTO를 사용하도록 수정

[배포] 권한 구현 수정 외

---

docs/promo.md
src/main/java/com/jandi/band_backend/promo/controller/PromoController.java
src/main/java/com/jandi/band_backend/promo/dto/PromoReqDTO.java
src/main/java/com/jandi/band_backend/promo/dto/PromoRespDTO.java
src/main/java/com/jandi/band_backend/promo/entity/Promo.java
src/main/java/com/jandi/band_backend/promo/repository/PromoRepository.java
src/main/java/com/jandi/band_backend/promo/service/PromoService.java

fix: 공연 홍보

---

MONITORING_GUIDE.md
build.gradle
docker-compose.monitoring.yml
docs/promo.md
monitoring/grafana/dashboards/jandi-application-dashboard.json
monitoring/grafana/provisioning/dashboards/dashboard.yml
monitoring/grafana/provisioning/datasources/prometheus.yml
monitoring/prometheus/prometheus.yml
src/main/java/com/jandi/band_backend/config/AdvancedMetricsConfig.java
src/main/java/com/jandi/band_backend/config/MetricsConfig.java
src/main/java/com/jandi/band_backend/config/MetricsInterceptor.java
src/main/java/com/jandi/band_backend/config/SecurityConfig.java
src/main/java/com/jandi/band_backend/config/SecurityMetricsConfig.java
src/main/java/com/jandi/band_backend/config/WebConfig.java
src/main/java/com/jandi/band_backend/health/HealthCheckController.java
src/main/java/com/jandi/band_backend/promo/controller/PromoController.java
src/main/java/com/jandi/band_backend/promo/dto/PromoReqDTO.java
src/main/java/com/jandi/band_backend/promo/dto/PromoRespDTO.java
src/main/java/com/jandi/band_backend/promo/service/PromoService.java
src/main/resources/logback-spring.xml
start-monitoring.bat
start-monitoring.sh

[배포] 회원 탈퇴 기능 추가

---

src/main/java/com/jandi/band_backend/invite/dto/InviteLinkRespDTO.java
src/main/java/com/jandi/band_backend/invite/service/InviteService.java

프론트 요청에 따라 초대동아리/팀의 id도 넘겨주도록 변경
- Closes #이슈번호
- 프론트 요청에 따라 InviteLinkRespDTO에 id 추가

Fix: InviteLinkRespDTO에 id 추가

---

src/main/java/com/jandi/band_backend/promo/service/PromoService.java

- DB에서 새 이미지를 추가하거나 기존 이미지를 업데이트하는 로직으로 수정
- 코드 참조
- hotfix

hotfix: 이미지 처리 로직 고침

---

src/main/java/com/jandi/band_backend/auth/service/AuthService.java
src/main/java/com/jandi/band_backend/club/repository/ClubMemberRepository.java

- Closes #이슈번호
- 제곧내
- 전에 회의하면서 말나왔던거 같은데... 구현을 안했었네욯ㅎ

fix: 동아리장은 회원탈퇴 못하게 막아둠

---

src/main/java/com/jandi/band_backend/config/SecurityConfig.java
src/main/java/com/jandi/band_backend/manage/repository/ReportReasonRepository.java
src/main/java/com/jandi/band_backend/promo/controller/PromoCommentReportController.java
src/main/java/com/jandi/band_backend/promo/controller/PromoReportController.java
src/main/java/com/jandi/band_backend/promo/dto/PromoCommentReportReqDTO.java
src/main/java/com/jandi/band_backend/promo/dto/PromoCommentReportRespDTO.java
src/main/java/com/jandi/band_backend/promo/dto/PromoReportReqDTO.java
src/main/java/com/jandi/band_backend/promo/dto/PromoReportRespDTO.java
src/main/java/com/jandi/band_backend/promo/repository/PromoCommentReportRepository.java
src/main/java/com/jandi/band_backend/promo/repository/PromoReportRepository.java
src/main/java/com/jandi/band_backend/promo/service/PromoCommentReportService.java
src/main/java/com/jandi/band_backend/promo/service/PromoReportService.java

- Closes #이슈번호
- 공연홍보, 공연홍보댓글 신고 api 추가

feat: 공연홍보, 공연홍보댓글 신고 api 추가

---

docs/team-teamtimetable.md
src/main/java/com/jandi/band_backend/global/exception/TimetableNotFoundException.java
src/main/java/com/jandi/band_backend/global/util/EntityValidationUtil.java
src/main/java/com/jandi/band_backend/team/service/PracticeScheduleService.java
src/main/java/com/jandi/band_backend/team/service/TeamService.java
src/main/java/com/jandi/band_backend/team/service/TeamTimetableService.java
src/main/java/com/jandi/band_backend/user/repository/UserTimetableRepository.java

refactor: 유틸 메서드를 활용한 서비스 코드 리팩토링 (팀)

---

src/main/java/com/jandi/band_backend/club/service/ClubEventService.java
src/main/java/com/jandi/band_backend/club/service/ClubService.java
src/main/java/com/jandi/band_backend/global/util/EntityValidationUtil.java

refactor: 유틸 메서드를 활용한 서비스 코드 리팩토링 (동아리)

---

src/test/java/com/jandi/band_backend/club/controller/ClubEventControllerTest.java

- Closes #이슈번호
- 동아리 일정 추가 api 테스트 코드 추가

test:동아리 일정 추가 api 테스트 코드 추가

---

src/main/java/com/jandi/band_backend/poll/dto/PollReqDTO.java
src/main/java/com/jandi/band_backend/poll/dto/PollSongReqDTO.java
src/main/java/com/jandi/band_backend/poll/service/PollService.java

- 제곧내
- convertToVotedMark 메서드에서 투표 타입이 null이거나 비어있을 경우 BadRequestException을 발생시키도록 수정
- applySortingForResult 메서드에서 정렬 기준이 null이거나 비어있을 경우 BadRequestException을 발생시키도록 수정

fix: 투표 타입 및 정렬 기준에 대한 유효성 검사 추가

---

docs/promo-promo.md
src/main/java/com/jandi/band_backend/promo/service/PromoService.java

fix: 공연홍보글 관람료 음수값 검증 추가
